// JournalPrompts.ts
export const prompts = {
  freeWriting: [
    "Write about anything on your mind right now.",
    "What's been bothering you lately?",
    "Describe your day as if you're telling a story.",
    "What are you avoiding that you need to face?",
    "What does your ideal future look like?",
    "If your emotions could speak, what would they say today?",
    "What's something you wish someone asked you about?",
    "Write freely about the last moment you felt truly at peace.",
    "What thoughts have been repeating in your head lately?",
    "If today had a theme song, what would it be and why?",
    "What tension or stress is sitting in your body right now?",
    "What memory popped into your mind unexpectedly today?",
    "Write about something you can't say out loud yet.",
    "What do you need more of in your life right now?",
    "Let your mind spill, no structure, no rules, just words.",
  ],
  guided: [
    "What are three things you're proud of recently?",
    "Who has had the biggest impact on your life and why?",
    "What is one fear you've overcome and how did you do it?",
    "Describe a recent challenge and what it taught you.",
    "What is something you're currently working to improve?",
    "What is a belief you no longer agree with, and why?",
    "Describe a moment that changed you significantly.",
    "What habit has improved your life the most?",
    "What is something you’re holding onto that you need to release?",
    "What does self-love look like for you right now?",
    "Write about a time you surprised yourself in a good way.",
    "Who in your life makes you feel safe, and why?",
    "What is a goal you're scared to admit you want?",
    "What would your younger self be most proud of today?",
    "What is one boundary you need to set or reinforce?",
  ],
  gratitude: [
    "What are three things you're grateful for today?",
    "Write about someone who made your day better.",
    "Describe a recent moment that brought you joy.",
    "What comforts you when you're feeling low?",
    "List small things that made you smile this week.",
    "What is a personal strength you're grateful to have?",
    "What everyday thing do you often overlook but appreciate now?",
    "Write about a place that brings you comfort.",
    "What is something stressful that ended up teaching you something valuable?",
    "What is something simple you're grateful exists in your life?",
    "Who is someone that always supports you, even in subtle ways?",
    "What is a struggle you're grateful you went through because it shaped you?",
    "What is something about your health or body you're thankful for today?",
    "Write about a moment of kindness you recently witnessed.",
    "What opportunity or privilege are you grateful to have right now?",
  ],
};
